### ISSUE TITLE
Opensource Checklist

### ISSUE THREAD

**Issue by andrewjstone** [vmware/haret#84]
- [x] Add license header to all files
- [x] Change repo name to `haret`  (Requires Admin Permissions)
- [x] Fill in project short description in GitHub (Requires Admin Permissions)
- [ ] Setup a public mailing list (v2r2 channel on irc already exists, but should be renamed to haret)
- [ ] Document Release strategy? (We don't really have a release strategy at this stage)
- [x] .travis.yml

**Comment by andrewjstone** [comment]
No decision on discussion channels or release strategy yet. Closing this issue as haret is already open.
